# dns_resolver_addr - Required for http transport- IP address of DNS resolver.
#
dns_resolver_addr: ~


# http_endpoint_url - Required for http transport - URL of the HTTP Endpoint.
#
http_endpoint_url: ~


# process_commandline - Required for process transport - Process Command Line
#
process_commandline: ~


# listen_addr - Optional - IP Address of the network interface on which to listen.
#                          Can be given on the command line instead.
#                          Default value: 127.0.0.1
listen_addr: ~


# listen_port - Optional - TCP Port Number on which to listen.
#                          Can be given on the command line instead.
#                          Default value: 2575
listen_port: ~

# logfile - Optional - Path to which to write a debug log file.
#                      Can be given on the command line instead.
#                      Default value: null (no logging)
logfile: ~
